# Generated by Django 5.2.3 on 2025-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('school', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('internship_position', models.CharField(max_length=100)),
                ('internship_type', models.CharField(choices=[('Voluntary', 'Voluntary'), ('Academic', 'Academic')], max_length=10)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('required_hrs', models.PositiveIntegerField()),
                ('resume_file_name', models.FileField(upload_to='resumes/')),
                ('application_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
