# Generated by Django 5.2.3 on 2025-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
