# Generated by Django 5.2.3 on 2025-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillapp', '0002_internshipapplication_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='status_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Not Proceed', 'Not Proceed')], default='Pending', max_length=50),
        ),
    ]
