# Generated by Django 5.2.3 on 2025-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillapp', '0003_internshipapplication_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='status_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Not Proceed', 'Not Proceed'), ('Finished', 'Finished')], default='Pending', max_length=50),
        ),
    ]
