# Generated by Django 5.2.3 on 2025-06-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillapp', '0004_alter_internshipapplication_status_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipapplication',
            old_name='status_type',
            new_name='status',
        ),
    ]
